modules:
  - lib/gitlab
  - lib/jira
  - server
  - server/targets/server-linux
  - server/targets/server-macos
  - cli
  - cli/targets/cli-linux
  - cli/targets/cli-macos
  - cli/targets/cli-windows
